# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Timezone
timezone: America/Sao_Paulo

# jekyll-seo-tag settings
title: Daniel Rodrigues
tagline: Sou Analista de Infraestrutura Pleno com foco em ambientes cloud e híbridos, atuando principalmente com soluções Microsoft Azure e Microsoft 365.
description: >-
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

# SITE URL FINAL (sem barra no final)
url: "https://danielrodrigues7.github.io"
baseurl: "/bloog"

github:
  username: DanielRodrigues7

twitter:
  username: therafs

social:
  name: Daniel Rodrigues
  email: daniel07.rodrigues@hotmail.com
  links:
    - https://www.linkedin.com/in/daniel-rodrigues-358b41121/
    - https://github.com/DanielRodrigues7

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider:

# Theme mode (light/dark)
theme_mode:

cdn:

# Your avatar (use assets/img/avatar.jpg)
avatar: /assets/img/avatar.jpg

social_preview_image:

toc: true

comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

# Self-hosted static assets (deixe TRUE)
assets:
  self_host:
    enabled: true
    env: production

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
